### PR TITLE
Add gw5000 txt file

### PR DESCRIPTION
**Pull request by vandan-revanur**
This PR adds the geometry database for the GW5k dataset.

### CODE REVIEW

**Comment by ndattani** [comment]
Thank you! It would be nice if each entry had a format like this:
```
NAME = C39H56O5:GW5000.v0

# Number of atoms: 100
# Common name(s): Unknown
# InChI=1S/C39H56O5/c1-25(40)44-31-15-16-36(6)29(35(31,4)5)14-17-37(7)30(36)22-28(41)32-27-23-34(2,3)18-20-39(27,21-19-38(32,37)8)33(42)43-24-26-12-10-9-11-13-26/h9-13,27,29-32H,14-24H2,1-8H3/t27-,29-,30+,31-,32-,36-,37+,38+,39-/m0/s1\n']]

# SMILES: CC(=O)O[C@H]1CC[C@]2([C@H](C1(C)C)CC[C@@]1([C@@H]2CC(=O)[C@H]2[C@@]1(C)CC[C@@]1([C@H]2CC(C)(C)CC1)C(=O)OCc1ccccc1)C)C

# SMARTS: _______

# Reference Code: URACOG
# CAS Number: _______
# Source paper: https://doi.org/10.1038/s41597-020-0385-y (Stuke et al.)
# Source data host: https://doi.org/10.14459/2019mp1507656 
# Source download link: https://dataserv.ub.tum.de/index.php/s/m1507656 , Filename: df_5k.json
# Source method: PBE_TS-vdW
# Properties: Number of electrons = 330, Spin multiplicity = Singlet, Electronic state = Ground, Charge = 0, Point group = Unknown
# Date added: 2 April 2023 (Vandan Revanur)
# Date modified: 3 April 2023 (Vandan Revanur)
# Date modified: ____

N      38.06444308      36.88172453      30.43904239
H      37.13229674      36.52932952      30.63502894
H      37.87447083      34.45373990      31.61484874
H      38.29175516      34.28685128      29.88425431
H      39.43188162      36.70033091      26.00124438
C      36.88232957      40.90658315      31.61111721
C      36.87420304      42.07232240      34.16091645
C      35.66822877      41.73380212      33.54463238
H      34.72213495      41.92510336      34.05079207
C      35.67474519      41.15404148      32.27622305
H      34.73170756      40.89204403      31.79327694
C      36.87670969      40.26146213      30.25307979
H      35.94045809      40.46280384      29.72064436
...
```

**Comment by ndattani** [comment]
In your latest commit, the first geometry's entry looks like this:

```
NAME = C10H15NO2S2:GW500.v0
# Number of atoms: 30
# common name: None
InChI=1S/C10H15NO2S2/c1-5-8-7(3)15-10(14)11(8)6(2)9(12)13-4/h6H,5H2,1-4H3/t6-/m1/s1

# SMILES : COC(=O)[C@H](n1c(=S)sc(c1CC)C)C
# Smarts: None
# Reference code: FOVWES
# cas: None
# Source paper: https://doi.org/10.1038/s41597-020-0385-y (Stuke et al.)
# Source data host: https://doi.org/10.14459/2019mp1507656
# Source download link: https://dataserv.ub.tum.de/index.php/s/m1507656 , Filename: df_5k.json
# Source method: PBE_TS-vdW
# Date added: 2 April 2023 (Vandan Revanur)
# Date modified: 2023-04-05 21:45:50.915892 (Vandan Revanur)

30

S      36.75934695      47.20389183      45.77859533 
C      37.56022072      46.42557279      47.12244195 
N      38.41486173      47.34224375      47.69527868 
```

I have the following comments: 
- [x] Please change "None" to "Unknown" (this is actually what I suggested to say in my original proposal above)
- [x]  "Number of atoms: 30" can end with a period (`.`)  so that when we want to search for all molecules with "XX" atoms, we can search "XX." Right now if we search "30" we'll find thousands of results, but when we change it to "Number of atoms: 30." and we search "30." we will be able to conveniently filter out all cases that have 30 atoms.
- [x] Your InChI line doesn't start with a hash symbol, so the parser won't know that this is a "comment"
- [x] Can we have blank lines around the SMARTS and SMILES lines as shown in my original proposal? This makes everything look neater when the SMILES/SMARTS/InChI lines are so long that they wrap around by default in Vi/Vim or whatever other editor.
- [x] After the last comment and before the XYZ coordinates begin, you have the number "30" again. This is no longer needed because we have "Number of atoms = 30." included at the top.
- [x] In my proposal above, I also suggested to include a line like the following, right before the "Date added" line:
```
# Properties: Number of electrons = 330, Spin multiplicity = Singlet, Electronic state = Ground, Charge = 0, Point group = Unknown
```
All of our entries in the GW5000 dataset are expected to have the same values for all of these properties except for the number of electrons. The number of electrons can be obtained for the molecule: C10H15NO2S2 by the formula 6x10 + 1x15 + 7x1 + 8x2 + 16x2, because each of the 10 carbon atoms has 6 electrons, each of the 16 hydrogen atoms has 1 electron, etc.

[Almost 5 years ago I asked if there was a program that could quickly do that calculation for me, but it got deleted](https://user-images.githubusercontent.com/1163013/230537108-aef203f8-7c3f-45e3-b2f7-53d42b50d3c4.png). That was about 2 years before I got MMSE launched, so maybe I can ask it again in a friendlier community, but I suspect the answer is still no!

Perhaps you can test all of this on the GW27 dataset [here](https://github.com/HPQC-LABS/goDatabase/blob/master/benchmark_sets/GW27.txt) first?

**Comment by vandan-revanur** [comment]
> here

I have now made all the changes suggested by you.
I have a comment is about this suggestion of yours:

`After the last comment and before the XYZ coordinates begin, you have the number "30" again. This is no longer needed because we have "Number of atoms = 30." included at the top.`

My opinion is that this is good to have the number of atoms, since this a part of the xyzBlock, and it is required when reading in the information of the xyz coordinates.

For example using rdkit, one can do :

Chem.MolFromXYZBlock(xyz_string)

If the 30 is not included then one will get an error like this:
`[13:44:04] Unable to recognize the number of atoms: cannot convert 
`
So I would say it is good to retain the number of atoms above the xyz block.

**Comment by vandan-revanur** [comment]
> In your latest commit, the first geometry's entry looks like this:
> 
> ```
> NAME = C10H15NO2S2:GW500.v0
> # Number of atoms: 30
> # common name: None
> InChI=1S/C10H15NO2S2/c1-5-8-7(3)15-10(14)11(8)6(2)9(12)13-4/h6H,5H2,1-4H3/t6-/m1/s1
> 
> # SMILES : COC(=O)[C@H](n1c(=S)sc(c1CC)C)C
> # Smarts: None
> # Reference code: FOVWES
> # cas: None
> # Source paper: https://doi.org/10.1038/s41597-020-0385-y (Stuke et al.)
> # Source data host: https://doi.org/10.14459/2019mp1507656
> # Source download link: https://dataserv.ub.tum.de/index.php/s/m1507656 , Filename: df_5k.json
> # Source method: PBE_TS-vdW
> # Date added: 2 April 2023 (Vandan Revanur)
> # Date modified: 2023-04-05 21:45:50.915892 (Vandan Revanur)
> 
> 30
> 
> S      36.75934695      47.20389183      45.77859533 
> C      37.56022072      46.42557279      47.12244195 
> N      38.41486173      47.34224375      47.69527868 
> ```
> 
> I have the following comments:
> 
> * [ ]  Please change "None" to "Unknown" (this is actually what I suggested to say in my original proposal above)
> * [ ]   "Number of atoms: 30" can end with a period (`.`)  so that when we want to search for all molecules with "XX" atoms, we can search "XX." Right now if we search "30" we'll find thousands of results, but when we change it to "Number of atoms: 30." and we search "30." we will be able to conveniently filter out all cases that have 30 atoms.
> * [ ]  Your InChI line doesn't start with a hash symbol, so the parser won't know that this is a "comment"
> * [ ]  Can we have blank lines around the SMARTS and SMILES lines as shown in my original proposal? This makes everything look neater when the SMILES/SMARTS/InChI lines are so long that they wrap around by default in Vi/Vim or whatever other editor.
> * [ ]  After the last comment and before the XYZ coordinates begin, you have the number "30" again. This is no longer needed because we have "Number of atoms = 30." included at the top.
> * [ ]  In my proposal above, I also suggested to include a line like the following, right before the "Date added" line:
> 
> ```
> # Properties: Number of electrons = 330, Spin multiplicity = Singlet, Electronic state = Ground, Charge = 0, Point group = Unknown
> ```
> 
> All of our entries in the GW5000 dataset are expected to have the same values for all of these properties except for the number of electrons. The number of electrons can be obtained for the molecule: C10H15NO2S2 by the formula 6x10 + 1x15 + 7x1 + 8x2 + 16x2, because each of the 10 carbon atoms has 6 electrons, each of the 16 hydrogen atoms has 1 electron, etc.
> 
> [Almost 5 years ago I asked if there was a program that could quickly do that calculation for me, but it got deleted](https://user-images.githubusercontent.com/1163013/230537108-aef203f8-7c3f-45e3-b2f7-53d42b50d3c4.png). That was about 2 years before I got MMSE launched, so maybe I can ask it again in a friendlier community, but I suspect the answer is still no!
> 
> Perhaps you can test all of this on the GW27 dataset [here](https://github.com/HPQC-LABS/goDatabase/blob/master/benchmark_sets/GW27.txt) first?



> In your latest commit, the first geometry's entry looks like this:
> 
> ```
> NAME = C10H15NO2S2:GW500.v0
> # Number of atoms: 30
> # common name: None
> InChI=1S/C10H15NO2S2/c1-5-8-7(3)15-10(14)11(8)6(2)9(12)13-4/h6H,5H2,1-4H3/t6-/m1/s1
> 
> # SMILES : COC(=O)[C@H](n1c(=S)sc(c1CC)C)C
> # Smarts: None
> # Reference code: FOVWES
> # cas: None
> # Source paper: https://doi.org/10.1038/s41597-020-0385-y (Stuke et al.)
> # Source data host: https://doi.org/10.14459/2019mp1507656
> # Source download link: https://dataserv.ub.tum.de/index.php/s/m1507656 , Filename: df_5k.json
> # Source method: PBE_TS-vdW
> # Date added: 2 April 2023 (Vandan Revanur)
> # Date modified: 2023-04-05 21:45:50.915892 (Vandan Revanur)
> 
> 30
> 
> S      36.75934695      47.20389183      45.77859533 
> C      37.56022072      46.42557279      47.12244195 
> N      38.41486173      47.34224375      47.69527868 
> ```
> 
> I have the following comments:
> 
> * [ ]  Please change "None" to "Unknown" (this is actually what I suggested to say in my original proposal above)
> * [ ]   "Number of atoms: 30" can end with a period (`.`)  so that when we want to search for all molecules with "XX" atoms, we can search "XX." Right now if we search "30" we'll find thousands of results, but when we change it to "Number of atoms: 30." and we search "30." we will be able to conveniently filter out all cases that have 30 atoms.
> * [ ]  Your InChI line doesn't start with a hash symbol, so the parser won't know that this is a "comment"
> * [ ]  Can we have blank lines around the SMARTS and SMILES lines as shown in my original proposal? This makes everything look neater when the SMILES/SMARTS/InChI lines are so long that they wrap around by default in Vi/Vim or whatever other editor.
> * [ ]  After the last comment and before the XYZ coordinates begin, you have the number "30" again. This is no longer needed because we have "Number of atoms = 30." included at the top.
> * [ ]  In my proposal above, I also suggested to include a line like the following, right before the "Date added" line:
> 
> ```
> # Properties: Number of electrons = 330, Spin multiplicity = Singlet, Electronic state = Ground, Charge = 0, Point group = Unknown
> ```
> 
> All of our entries in the GW5000 dataset are expected to have the same values for all of these properties except for the number of electrons. The number of electrons can be obtained for the molecule: C10H15NO2S2 by the formula 6x10 + 1x15 + 7x1 + 8x2 + 16x2, because each of the 10 carbon atoms has 6 electrons, each of the 16 hydrogen atoms has 1 electron, etc.
> 
> [Almost 5 years ago I asked if there was a program that could quickly do that calculation for me, but it got deleted](https://user-images.githubusercontent.com/1163013/230537108-aef203f8-7c3f-45e3-b2f7-53d42b50d3c4.png). That was about 2 years before I got MMSE launched, so maybe I can ask it again in a friendlier community, but I suspect the answer is still no!
> 
> Perhaps you can test all of this on the GW27 dataset [here](https://github.com/HPQC-LABS/goDatabase/blob/master/benchmark_sets/GW27.txt) first?

I have now made all the changes suggested by you.
I have a comment is about this suggestion of yours:

`After the last comment and before the XYZ coordinates begin, you have the number "30" again. This is no longer needed because we have "Number of atoms = 30." included at the top.`

My opinion is that this is good to have the number of atoms, since this a part of the xyzBlock, and it is required when reading in the information of the xyz coordinates.

For example using rdkit, one can do :

Chem.MolFromXYZBlock(xyz_string)

If the 30 is not included then one will get an error like this:
`[13:44:04] Unable to recognize the number of atoms: cannot convert 
`
So I would say it is good to retain the number of atoms above the xyz block.

**Comment by vandan-revanur** [comment]
I have now made all the changes suggested by you.
I have a comment is about this suggestion of yours:

`After the last comment and before the XYZ coordinates begin, you have the number "30" again. This is no longer needed because we have "Number of atoms = 30." included at the top.`

My opinion is that this is good to have the number of atoms, since this a part of the xyzBlock, and it is required when reading in the information of the xyz coordinates.

For example using rdkit, one can do :

Chem.MolFromXYZBlock(xyz_string)

If the 30 is not included then one will get an error like this:
`[13:44:04] Unable to recognize the number of atoms: cannot convert 
`
So I would say it is good to retain the number of atoms above the xyz block.

**Comment by ndattani** [comment]
Thanks! We can keep the 30 there in order to be more user-friendly to programs that require it, such as rdkit. 
Would rdkit be able to read our data with all these "comments" though? Or would we have to write a parser in order for rdkit to be able to read our format (or manually copy and paste the XYZ coordinates and number of atoms into the rdkit input)?

If we would have to manually copy and paste the XYZ coordinates and number of atoms into rdkit input, then it won't be possible to work with a dataset like GW5000 which has 5000 molecules, so in that case we would have to modify rdkit so that it can read our format that has "comments" in it. If we are writing that type of parser anyway, then there seems to be no need for "duplicating" the line that gives the number of atoms.

<hr>

Finally, since you haven't squashed the commits yet, I wonder what you think about the `.` at the end of the number of atoms? I originally thought that it would help me find molecules of a certain size, so if I want a molecule with 30 atoms I would search "30."  However, even without the `.` I can search "Number of atoms: 30" and the same molecule will be found. If you cannot see any advantage of having the dot at the end, I don't mind if you remove the `.` before your final squash of the existing commits in this pull request. 

I'm basically ready to approve this pull request.

**Comment by vandan-revanur** [comment]
rdkit would **not** be able to read directly. rdkit would not understand comments that we have put.
However for debugging purposes I still think it is worthwhile to keep the number of atoms, since one can quickly create an rdkit mol object by copy pasting for a few molecules. 

I agree that it might not be useful for thousands of molecules on a large scale, however I think it is worthwhile for debugging. If you strongly feel it is unnecessary then I can remove it.

Regarding the dot after the number of atoms, I feel it is okay to have it as it could help in a quick search.

The squash will happen once you approve the PR. I will squash all of them with a single commit and merge the PR into the master.

**Comment by ndattani** [comment]
For rdkit: Copying and pasting won't work for 5000 molecules.  It will only work if we are doing it for a very small number of molecules. If we're only dealing with a small number of molecules, for debugging purposes, it should be easy enough to copy and paste the number of atoms separately from line 2 of the molecule's entry.

For the period at the end of the number of atoms: I no longer see any advantage of having the period there. If we want to search for all molecules with 30 atoms, we can just search for "Number of atoms: 30" and it should be just as good as searching for "30.". Actually while typing that I noticed that if an X,Y, or Z coordinate has a numerical value of 30.5692, then searching "30." will find that XYZ coordinate too, and for a dataset with 62000 molecules, this might happen so many times that we'll never practically find the 30-atom molecule that we're seeking. 

Therefore I would recommend to remove the "." and the extra line with number of atoms for now, and we can always modify it later in a new pull request if we become convinced that those options are better. I'm considering to ask a question on MMSE with a proposed format, and for people to answer with the format that they think would be best. Perhaps you can start off that thread with an answer that contains your favorite format (e.g. including the number of atoms for compatibility with rdkit, and any other suggestions that you might have). Then we can gauge what is best based on the answers we get, and the voting and comments.

**Comment by ndattani** [comment]
@vandan-revanur The file currently says: 
```
NAME = C10H15NO2S2:GW500.v0
```
with GW500 instead of GW5000.

**Comment by vandan-revanur** [comment]
The GW500 typo is now rectified.

**Comment by ndattani** [comment]
Thank you for that! I'm still waiting for the duplicate entries to be labelled unambiguously. Also, I noticed that we have `InChI =` twice here:
```
# InChI = InChI=1S/C9H11N3S/c1-7-2-3-10-8(6-7)12-5-4-11-9(12)13/h2-3,6H,4-5H2,1H3,(H,11,13)
```

**Comment by vandan-revanur** [comment]
I will implement the duplicate entry check soon. And will also push a fix for the inchi thing.

**Comment by ndattani** [comment]
@vandan-revanur  I'm not sure what procedure you're using to find duplicates, but the following might help:
```
grep "NAME" gw5000.txt > gw5000_grepNAME.txt                    # Takes 1 second
sort gw5000_grepNAME.txt | uniq -cd > gw5000_grepNAME_sort.txt  # Takes 1 second
```
The file `gw5000_grepNAME_sort.txt` has 544 lines, meaning that only about 10% of the molecules have duplicate chemical formulas:
```
      2 NAME = C10H10N2O2:GW5000.v0
      2 NAME = C10H10N2O2S:GW5000.v0
      2 NAME = C10H10N4:GW5000.v0
      3 NAME = C10H10O4:GW5000.v0
      2 NAME = C10H11Br3O2:GW5000.v0
      2 NAME = C10H11N3OS:GW5000.v0
      2 NAME = C10H11N5O:GW5000.v0
```
The number on the left is the number of times that the chemical formula appeared. I think the highest is 5.

The program `sed` can replace the second occurrence of  C10H10N2O2 with  C10H10N2O2(2), and then the second occurence of  C10H10N2O2(2) with  C10H10N2O2(3) and the second occurrence of  C10H10N2O2(3) with  C10H10N2O2(4), etc. Some of the many SE threads about this are mentioned here: https://stackoverflow.com/q/70021339/1271772.

The following Vi/Vim and `sed` commands helped me:
```
:%s/  */ /g                                                                # Remove white spaces between `/` characters
:%s/\/\n/(2)\/2' gw5000.txt\r/                                             # Replace /\n with (2)/2' gw5000.txt/\r because this is what we want for the sed command
sed -i -z 's/NAME = C10H10N2O2/NAME = C10H10N2O2(2)/2'   gw5000.txt        # The 2 at the end of the regular sed command makes the substitution only happen at the second occurrence, and this only works if we use `-z` (or maybe if we tell sed to do this on "all lines", the -z treats the whole file as one line)
```

**Comment by ndattani** [comment]
Thanks! I'm curious how you dealt with the duplicates in the end? I thought maybe the reason it was taking longer than some of the other updates, was possibly because of the way that you were searching for the duplicates, which is why I also started to think about ways to do it efficiently. This might be worth considering for the 62,000 molecules.

**Review by ndattani — APPROVED** [review]
I approve these changes subject to squashing of the commits :)

**Comment by vandan-revanur** [comment]
> Thanks! I'm curious how you dealt with the duplicates in the end? I thought maybe the reason it was taking longer than some of the other updates, was possibly because of the way that you were searching for the duplicates, which is why I also started to think about ways to do it efficiently. This might be worth considering for the 62,000 molecules.

I agree that this is a good and fast method. However, I think it is better to add this functionality in the python code where we generate the database. So I implemented this in my code by keeping a track of names that we add into the database and when we encounter a new one which is a duplicate, I increment a counter.

**Comment by ndattani** [comment]
I think the way that you did it is perfectly fine, and can be used for larger data sets in the future. I was mainly thinking about solutions using the tools which I'm familiar (vi/vim, sed, grep, sort, etc.) in case the reason it was taking long was due to difficulty.

**Pull request merged**
